import React, { useState, useEffect, useMemo, useRef } from 'react';
import {
  FolderTree,
  Plus,
  FileCode,
  Trash2,
  ArrowRight,
  Layers,
  FilePlus,
  ShieldCheck,
  FolderGit2,
  HardDrive,
  Info,
  Clock,
  Code,
  FileText,
  CheckCircle2,
  BarChart2,
  Eye,
  Search,
  RefreshCw,
  Copy,
  Check,
  FolderSearch,
  FolderUp,
  AlertCircle,
  Upload,
  ListTree,
  LayoutGrid,
  ExternalLink,
} from 'lucide-react';
import { ProjectInfo, ProjectOverview } from '../types';
import { ProjectVisualSummary } from './ProjectVisualSummary';
import { GitStatusPanel } from './GitStatusPanel';
import { FileTreeNavigator } from './FileTreeNavigator';

interface ProjectManagerViewProps {
  projects: ProjectInfo[];
  activeProject: string;
  projectFiles: string[];
  activeFile: string;
  onSelectProject: (name: string) => void;
  onSelectFile: (file: string) => void;
  onRefreshProjects: () => void;
  onNavigateToAST?: () => void;
}

export function ProjectManagerView({
  projects,
  activeProject,
  projectFiles,
  activeFile,
  onSelectProject,
  onSelectFile,
  onRefreshProjects,
  onNavigateToAST,
}: ProjectManagerViewProps) {
  // Navigation mode within Project Manager: 'dashboard' or 'files'
  const [managerTab, setManagerTab] = useState<'dashboard' | 'files'>('dashboard');

  // Overview metrics state
  const [projectOverviews, setProjectOverviews] = useState<ProjectOverview[]>([]);
  const [loadingOverviews, setLoadingOverviews] = useState(false);
  const [searchFilter, setSearchFilter] = useState('');

  // Modal & form states
  const [newProjName, setNewProjName] = useState('');
  const [newProjPath, setNewProjPath] = useState('');
  const [newProjDesc, setNewProjDesc] = useState('');
  const [newFileName, setNewFileName] = useState('');
  const [showNewProjectModal, setShowNewProjectModal] = useState(false);
  const [showNewFileModal, setShowNewFileModal] = useState(false);
  const [pathAutoGenerated, setPathAutoGenerated] = useState(true);
  const [auditReport, setAuditReport] = useState<any | null>(null);
  const [auditLoading, setAuditLoading] = useState(false);
  const [copiedPath, setCopiedPath] = useState<string | null>(null);

  // Scan Directory Modal States
  const [showScanModal, setShowScanModal] = useState(false);
  const [scanMode, setScanMode] = useState<'server' | 'browser'>('server');
  const [scanServerPath, setScanServerPath] = useState('/workspace');
  const [scanCustomName, setScanCustomName] = useState('');
  const [scanMaxFiles, setScanMaxFiles] = useState(150);
  const [scanLoading, setScanLoading] = useState(false);
  const [scanError, setScanError] = useState<string | null>(null);

  // Tree view file navigator & preview states
  const [fileViewMode, setFileViewMode] = useState<'tree' | 'grid'>('tree');
  const [activeFileContent, setActiveFileContent] = useState<string>('');
  const [loadingFileContent, setLoadingFileContent] = useState<boolean>(false);

  // Browser directory picker state
  const [browserFolderName, setBrowserFolderName] = useState('');
  const [browserFiles, setBrowserFiles] = useState<Array<{ path: string; content: string; size: number }>>([]);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Fetch project overview metrics
  const fetchOverviews = async () => {
    setLoadingOverviews(true);
    try {
      const res = await fetch('/api/projects/overview');
      if (res.ok) {
        const data = await res.json();
        setProjectOverviews(data);
      }
    } catch (err) {
      console.error('Failed to load project overviews', err);
    } finally {
      setLoadingOverviews(false);
    }
  };

  useEffect(() => {
    fetchOverviews();
  }, [projects]);

  // Fetch active file content for the preview panel
  useEffect(() => {
    if (!activeProject || !activeFile) return;
    let isMounted = true;
    setLoadingFileContent(true);
    fetch(`/api/projects/${encodeURIComponent(activeProject)}/file?path=${encodeURIComponent(activeFile)}`)
      .then((res) => (res.ok ? res.json() : null))
      .then((data) => {
        if (isMounted && data) {
          setActiveFileContent(data.content || '');
          setLoadingFileContent(false);
        }
      })
      .catch(() => {
        if (isMounted) setLoadingFileContent(false);
      });
    return () => {
      isMounted = false;
    };
  }, [activeProject, activeFile]);

  const handleOpenCreateModal = (targetFolder?: string) => {
    if (targetFolder) {
      setNewFileName(`${targetFolder}/`);
    } else {
      setNewFileName('');
    }
    setShowNewFileModal(true);
  };

  const handleRunAudit = async (targetProjectName?: string) => {
    const projToAudit = targetProjectName || activeProject;
    setAuditLoading(true);
    try {
      const res = await fetch(`/api/projects/${encodeURIComponent(projToAudit)}/isolation-audit`);
      const data = await res.json();
      setAuditReport(data);
    } catch (e) {
      console.error('Audit failed', e);
    } finally {
      setAuditLoading(false);
    }
  };

  // Auto-generate recommended path as user types name if path wasn't manually edited
  const handleNameChange = (val: string) => {
    setNewProjName(val);
    if (pathAutoGenerated) {
      const sanitized = val.toLowerCase().replace(/[^a-z0-9_-]/g, '-');
      setNewProjPath(sanitized ? `/workspace/${sanitized}` : '');
    }
  };

  const handlePathChange = (val: string) => {
    setNewProjPath(val);
    setPathAutoGenerated(false);
  };

  const handleCreateProject = async () => {
    if (!newProjName.trim()) return;
    const finalPath = newProjPath.trim() || `/workspace/${newProjName.trim().toLowerCase()}`;

    try {
      await fetch('/api/projects', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: newProjName.trim(),
          path: finalPath,
          description: newProjDesc.trim(),
        }),
      });

      // Initialize welcome file in the new project
      await fetch(`/api/projects/${encodeURIComponent(newProjName.trim())}/file`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          path: 'main.py',
          content: `# ${newProjName.trim()} - Workspace Isolado\n\ndef main():\n    print("Projeto ativo em ${finalPath}")\n\nif __name__ == "__main__":\n    main()\n`,
        }),
      });

      setNewProjName('');
      setNewProjPath('');
      setNewProjDesc('');
      setPathAutoGenerated(true);
      setShowNewProjectModal(false);
      onRefreshProjects();
      fetchOverviews();
      onSelectProject(newProjName.trim());
      onSelectFile('main.py');
    } catch (err) {
      console.error(err);
    }
  };

  // Handle Scanning Server Directory Path
  const handleScanServerDirectory = async () => {
    if (!scanServerPath.trim()) {
      setScanError('Por favor insira um caminho válido para escanear.');
      return;
    }

    setScanLoading(true);
    setScanError(null);

    try {
      const res = await fetch('/api/scan-directory', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          path: scanServerPath.trim(),
          name: scanCustomName.trim() || undefined,
          maxFiles: scanMaxFiles,
        }),
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || 'Erro ao escanear diretório.');
      }

      setShowScanModal(false);
      onRefreshProjects();
      fetchOverviews();
      onSelectProject(data.project);

      // Fetch newly scanned files to activate first one
      const filesRes = await fetch(`/api/projects/${encodeURIComponent(data.project)}/files`);
      if (filesRes.ok) {
        const files: string[] = await filesRes.json();
        if (files.length > 0) {
          onSelectFile(files[0]);
        }
      }
    } catch (err: any) {
      setScanError(err.message);
    } finally {
      setScanLoading(false);
    }
  };

  // Handle Browser Directory Selection (webkitdirectory)
  const handleBrowserFolderChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files || files.length === 0) return;

    setScanLoading(true);
    setScanError(null);

    const ALLOWED_EXTS = new Set([
      'py', 'ts', 'tsx', 'js', 'jsx', 'go', 'rs', 'java',
      'c', 'cpp', 'h', 'hpp', 'cs', 'rb', 'php', 'swift',
      'json', 'yaml', 'yml', 'toml', 'md', 'sql', 'html', 'css'
    ]);

    try {
      const parsedFiles: Array<{ path: string; content: string; size: number }> = [];
      let detectedRoot = '';

      for (let i = 0; i < files.length; i++) {
        const file = files[i];
        // webkitRelativePath format: "folderName/sub/file.ext"
        const relPath = file.webkitRelativePath || file.name;
        const parts = relPath.split('/');
        if (!detectedRoot && parts.length > 1) {
          detectedRoot = parts[0];
        }

        const ext = relPath.split('.').pop()?.toLowerCase();
        if (!ext || !ALLOWED_EXTS.has(ext)) continue;

        // Skip node_modules, git, dist
        if (
          relPath.includes('node_modules/') ||
          relPath.includes('.git/') ||
          relPath.includes('dist/') ||
          relPath.includes('build/') ||
          relPath.includes('__pycache__/')
        ) {
          continue;
        }

        // Limit individual file size to 1MB
        if (file.size > 1024 * 1024) continue;

        const content = await file.text();
        // Strip the top-level folder name from relative path so project path is clean
        const cleanRelPath = parts.length > 1 ? parts.slice(1).join('/') : file.name;
        parsedFiles.push({
          path: cleanRelPath,
          content,
          size: file.size,
        });

        if (parsedFiles.length >= scanMaxFiles) break;
      }

      if (parsedFiles.length === 0) {
        throw new Error('Nenhum arquivo de código suportado (.py, .ts, .go, .rs, etc.) encontrado na pasta selecionada.');
      }

      const folderName = detectedRoot || 'local-folder';
      setBrowserFolderName(folderName);
      setBrowserFiles(parsedFiles);
      if (!scanCustomName) {
        setScanCustomName(folderName.toLowerCase().replace(/[^a-z0-9_-]/g, '-'));
      }
    } catch (err: any) {
      setScanError(err.message);
    } finally {
      setScanLoading(false);
    }
  };

  // Submit Browser Files to Backend
  const handleImportBrowserFolder = async () => {
    if (browserFiles.length === 0) return;
    setScanLoading(true);
    setScanError(null);

    const projName = (scanCustomName || browserFolderName || 'imported-project')
      .toLowerCase()
      .replace(/[^a-z0-9_-]/g, '-');
    const projPath = `/workspace/${projName}`;

    try {
      const res = await fetch('/api/projects/batch-create', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: projName,
          path: projPath,
          description: `Imported from local folder '${browserFolderName}' (${browserFiles.length} files)`,
          files: browserFiles.map((f) => ({ path: f.path, content: f.content })),
        }),
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || 'Erro ao importar pasta do navegador.');
      }

      setShowScanModal(false);
      setBrowserFiles([]);
      setBrowserFolderName('');
      onRefreshProjects();
      fetchOverviews();
      onSelectProject(data.project);

      // Select first file
      if (browserFiles.length > 0) {
        onSelectFile(browserFiles[0].path);
      }
    } catch (err: any) {
      setScanError(err.message);
    } finally {
      setScanLoading(false);
    }
  };

  const handleDeleteProject = async (projectName: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (projects.length <= 1) {
      alert('Não é possível remover o único projeto ativo.');
      return;
    }

    if (
      !confirm(
        `Tem certeza de que deseja remover o projeto '${projectName}' e todo o seu contexto isolado?`
      )
    ) {
      return;
    }

    try {
      await fetch(`/api/projects/${encodeURIComponent(projectName)}`, {
        method: 'DELETE',
      });
      onRefreshProjects();
      fetchOverviews();
      const remaining = projects.filter((p) => p.name !== projectName);
      if (remaining.length > 0 && activeProject === projectName) {
        onSelectProject(remaining[0].name);
      }
    } catch (err) {
      console.error(err);
    }
  };

  const handleCreateFile = async () => {
    if (!newFileName.trim()) return;
    try {
      await fetch(`/api/projects/${encodeURIComponent(activeProject)}/file`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          path: newFileName.trim(),
          content: `# ${newFileName.trim()}\n\ndef main():\n    pass\n`,
        }),
      });
      setNewFileName('');
      setShowNewFileModal(false);
      onRefreshProjects();
      fetchOverviews();
      onSelectFile(newFileName.trim());
    } catch (err) {
      console.error(err);
    }
  };

  const handleDeleteFile = async (filePath: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (projectFiles.length <= 1) {
      alert('O projeto deve conter pelo menos um arquivo.');
      return;
    }

    if (!confirm(`Deseja remover o arquivo '${filePath}' do projeto '${activeProject}'?`)) {
      return;
    }

    try {
      await fetch(
        `/api/projects/${encodeURIComponent(activeProject)}/file?path=${encodeURIComponent(filePath)}`,
        { method: 'DELETE' }
      );
      onRefreshProjects();
      fetchOverviews();
      const remaining = projectFiles.filter((f) => f !== filePath);
      if (remaining.length > 0 && activeFile === filePath) {
        onSelectFile(remaining[0]);
      }
    } catch (err) {
      console.error(err);
    }
  };

  const handleCopyPath = (p: string, e: React.MouseEvent) => {
    e.stopPropagation();
    navigator.clipboard.writeText(p);
    setCopiedPath(p);
    setTimeout(() => setCopiedPath(null), 2000);
  };

  // Aggregate stats across all projects
  const aggregateStats = useMemo(() => {
    let totalLOC = 0;
    let totalFilesCount = 0;
    let totalFuncs = 0;
    let totalClassesCount = 0;

    for (const ov of projectOverviews) {
      totalLOC += ov.totalLines || 0;
      totalFilesCount += ov.fileCount || 0;
      totalFuncs += ov.totalFunctions || 0;
      totalClassesCount += ov.totalClasses || 0;
    }

    return {
      totalLOC,
      totalFilesCount,
      totalProjectsCount: projectOverviews.length,
      totalFuncs,
      totalClassesCount,
    };
  }, [projectOverviews]);

  // Filtered overviews by search term
  const filteredOverviews = useMemo(() => {
    if (!searchFilter.trim()) return projectOverviews;
    const q = searchFilter.toLowerCase();
    return projectOverviews.filter(
      (ov) =>
        ov.name.toLowerCase().includes(q) ||
        ov.path.toLowerCase().includes(q) ||
        ov.description?.toLowerCase().includes(q) ||
        ov.languages.some((l) => l.language.toLowerCase().includes(q))
    );
  }, [projectOverviews, searchFilter]);

  const currentProjectObj = projects.find((p) => p.name === activeProject);

  // Helper to format ISO date to readable string
  const formatDate = (isoString?: string) => {
    if (!isoString) return 'Recentemente';
    try {
      const d = new Date(isoString);
      return d.toLocaleDateString('pt-BR', {
        day: '2-digit',
        month: '2-digit',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      });
    } catch {
      return isoString;
    }
  };

  return (
    <div className="flex-1 flex flex-col h-full bg-[#0f172a] overflow-hidden">
      {/* Top Bar with Project Manager Sub-Navigation Tabs & Actions */}
      <div className="h-12 px-6 border-b border-slate-800 bg-[#11192e] flex items-center justify-between shrink-0 select-none">
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <FolderTree className="w-5 h-5 text-cyan-400" />
            <span className="font-semibold text-sm text-slate-100">Project Manager</span>
          </div>

          {/* Sub-navigation tabs: Dashboard vs Files */}
          <div className="flex items-center gap-1 bg-slate-900/80 p-0.5 rounded-lg border border-slate-800">
            <button
              onClick={() => setManagerTab('dashboard')}
              className={`px-3 py-1.5 rounded-md text-xs font-medium flex items-center gap-1.5 transition ${
                managerTab === 'dashboard'
                  ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 shadow-xs'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <BarChart2 className="w-3.5 h-3.5" />
              <span>Project Dashboard</span>
              <span className="text-[10px] px-1.5 py-0.2 rounded-full bg-slate-800 text-slate-400 font-mono">
                {projects.length}
              </span>
            </button>

            <button
              onClick={() => setManagerTab('files')}
              className={`px-3 py-1.5 rounded-md text-xs font-medium flex items-center gap-1.5 transition ${
                managerTab === 'files'
                  ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 shadow-xs'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <FileCode className="w-3.5 h-3.5" />
              <span>Arquivos do Workspace</span>
              <span className="text-[10px] px-1.5 py-0.2 rounded-full bg-slate-800 text-slate-400 font-mono">
                {projectFiles.length}
              </span>
            </button>
          </div>
        </div>

        {/* Global Actions in Header */}
        <div className="flex items-center gap-2">
          {managerTab === 'dashboard' && (
            <button
              onClick={fetchOverviews}
              disabled={loadingOverviews}
              className="p-1.5 hover:bg-slate-800 text-slate-400 hover:text-slate-200 rounded-lg border border-slate-800 transition"
              title="Atualizar métricas de projetos"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${loadingOverviews ? 'animate-spin' : ''}`} />
            </button>
          )}

          {/* SCAN DIRECTORY BUTTON */}
          <button
            onClick={() => {
              setShowScanModal(true);
              setScanError(null);
            }}
            className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-cyan-300 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition border border-slate-700 shadow-xs"
            title="Escanear diretório local e adicionar como configuração de projeto isolada"
          >
            <FolderSearch className="w-3.5 h-3.5 text-cyan-400" />
            <span>Escanear Diretório</span>
          </button>

          <button
            onClick={() => {
              setShowNewProjectModal(true);
              setPathAutoGenerated(true);
            }}
            className="px-3 py-1.5 bg-cyan-600 hover:bg-cyan-500 text-white rounded-lg text-xs font-semibold flex items-center gap-1.5 transition shadow-xs"
          >
            <Plus className="w-3.5 h-3.5" />
            <span>Novo Projeto</span>
          </button>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 overflow-auto p-6">
        <div className="max-w-6xl w-full mx-auto space-y-6">
          {/* TAB 1: PROJECT DASHBOARD VIEW */}
          {managerTab === 'dashboard' && (
            <div className="space-y-6 animate-in fade-in duration-150">
              {/* Aggregate KPI Stats Banner */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                <div className="bg-slate-900/90 p-4 rounded-xl border border-slate-800 space-y-1">
                  <div className="text-slate-400 text-xs font-medium flex items-center gap-1.5">
                    <FolderTree className="w-3.5 h-3.5 text-cyan-400" />
                    Projetos Ativos
                  </div>
                  <div className="text-2xl font-bold font-mono text-slate-100 tabular-nums">
                    {aggregateStats.totalProjectsCount}
                  </div>
                  <div className="text-[11px] text-slate-500">Workspaces registrados</div>
                </div>

                <div className="bg-slate-900/90 p-4 rounded-xl border border-slate-800 space-y-1">
                  <div className="text-slate-400 text-xs font-medium flex items-center gap-1.5">
                    <Code className="w-3.5 h-3.5 text-emerald-400" />
                    Total Linhas de Código (LOC)
                  </div>
                  <div className="text-2xl font-bold font-mono text-emerald-400 tabular-nums">
                    {aggregateStats.totalLOC}
                  </div>
                  <div className="text-[11px] text-slate-500">Em todos os projetos</div>
                </div>

                <div className="bg-slate-900/90 p-4 rounded-xl border border-slate-800 space-y-1">
                  <div className="text-slate-400 text-xs font-medium flex items-center gap-1.5">
                    <FileText className="w-3.5 h-3.5 text-purple-400" />
                    Arquivos Analisados
                  </div>
                  <div className="text-2xl font-bold font-mono text-purple-400 tabular-nums">
                    {aggregateStats.totalFilesCount}
                  </div>
                  <div className="text-[11px] text-slate-500">
                    {aggregateStats.totalFuncs} funções declaradas
                  </div>
                </div>

                <div className="bg-slate-900/90 p-4 rounded-xl border border-slate-800 space-y-1">
                  <div className="text-slate-400 text-xs font-medium flex items-center gap-1.5">
                    <ShieldCheck className="w-3.5 h-3.5 text-cyan-400" />
                    Camada de Isolamento
                  </div>
                  <div className="text-2xl font-bold font-mono text-cyan-400">100%</div>
                  <div className="text-[11px] text-slate-500">Zero contaminação cruzada</div>
                </div>
              </div>

              {/* Search and Filters Bar */}
              <div className="flex items-center justify-between gap-4">
                <div className="relative flex-1 max-w-md">
                  <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
                  <input
                    type="text"
                    placeholder="Filtrar projetos por nome, path ou linguagem..."
                    value={searchFilter}
                    onChange={(e) => setSearchFilter(e.target.value)}
                    className="w-full bg-slate-900 border border-slate-800 rounded-lg pl-9 pr-3 py-2 text-xs text-slate-200 focus:outline-none focus:border-cyan-500 font-mono"
                  />
                </div>

                <div className="text-xs text-slate-400 hidden sm:block">
                  Contexto Ativo: <span className="font-semibold text-cyan-400 font-mono">{activeProject}</span>
                </div>
              </div>

              {/* Visual Summary (Charts using Recharts) */}
              <ProjectVisualSummary
                projectOverviews={projectOverviews}
                activeProject={activeProject}
              />

              {/* Git Status Indicator & Summary Panel */}
              <GitStatusPanel
                activeProject={activeProject}
                projectPath={currentProjectObj?.path}
              />

              {/* Projects Overview Cards Grid */}
              <div className="space-y-3">
                {filteredOverviews.map((ov) => {
                  const isActive = activeProject === ov.name;
                  return (
                    <div
                      key={ov.name}
                      onClick={() => onSelectProject(ov.name)}
                      className={`p-5 rounded-2xl border transition cursor-pointer flex flex-col md:flex-row md:items-center justify-between gap-5 ${
                        isActive
                          ? 'bg-slate-900/90 border-cyan-500/60 shadow-lg shadow-cyan-950/20 ring-1 ring-cyan-500/40'
                          : 'bg-slate-900/50 border-slate-800 hover:border-slate-700 hover:bg-slate-900/70'
                      }`}
                    >
                      {/* Left: Project identity, path and metadata */}
                      <div className="space-y-2 flex-1 min-w-0">
                        <div className="flex items-center gap-2.5 flex-wrap">
                          <div className="flex items-center gap-2">
                            <FolderTree className={`w-4 h-4 ${isActive ? 'text-cyan-400' : 'text-slate-400'}`} />
                            <h4 className="font-semibold text-sm text-slate-100 truncate">{ov.name}</h4>
                          </div>

                          {isActive && (
                            <span className="text-[10px] px-2 py-0.5 rounded-full bg-cyan-950 border border-cyan-700/80 text-cyan-300 font-medium flex items-center gap-1">
                              <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-pulse"></span>
                              Ativo no Studio
                            </span>
                          )}

                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-slate-800 text-slate-300 font-mono">
                            {ov.fileCount} {ov.fileCount === 1 ? 'arquivo' : 'arquivos'}
                          </span>

                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-950/60 border border-emerald-800/80 text-emerald-300 font-mono">
                            ✓ 100% Isolado
                          </span>
                        </div>

                        {/* Isolated Path Bar */}
                        <div className="flex items-center gap-2">
                          <div
                            className="bg-slate-950 px-2.5 py-1 rounded-lg border border-slate-850 flex items-center gap-2 font-mono text-[11px] text-cyan-300 truncate max-w-xl group"
                            title={`Caminho isolado: ${ov.path}`}
                          >
                            <HardDrive className="w-3.5 h-3.5 text-slate-400 shrink-0" />
                            <span className="truncate">{ov.path}</span>
                          </div>

                          <button
                            onClick={(e) => handleCopyPath(ov.path, e)}
                            className="p-1 text-slate-400 hover:text-slate-200 hover:bg-slate-800 rounded transition"
                            title="Copiar caminho isolado"
                          >
                            {copiedPath === ov.path ? (
                              <Check className="w-3.5 h-3.5 text-emerald-400" />
                            ) : (
                              <Copy className="w-3.5 h-3.5" />
                            )}
                          </button>
                        </div>

                        {ov.description && (
                          <p className="text-xs text-slate-400 line-clamp-1">{ov.description}</p>
                        )}

                        {/* Languages mini pills */}
                        <div className="flex items-center gap-2 text-[11px] text-slate-400 pt-0.5">
                          <span className="text-slate-500">Linguagens:</span>
                          {ov.languages.length > 0 ? (
                            ov.languages.map((l) => (
                              <span
                                key={l.language}
                                className="font-mono text-[10px] text-slate-300 bg-slate-800/80 px-1.5 py-0.5 rounded uppercase"
                              >
                                {l.language} ({l.percentage}%)
                              </span>
                            ))
                          ) : (
                            <span className="text-slate-500 italic text-[10px]">Nenhum arquivo</span>
                          )}
                        </div>
                      </div>

                      {/* Middle: Quick Metrics Breakdown (LOC, Last modified, functions) */}
                      <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 md:border-l md:border-slate-800 md:pl-5 shrink-0 text-xs">
                        <div className="space-y-0.5">
                          <div className="text-slate-500 text-[10px] uppercase font-semibold tracking-wider">
                            Linhas (LOC)
                          </div>
                          <div className="font-mono font-bold text-slate-200 text-sm tabular-nums">
                            {ov.totalLines}
                          </div>
                          <div className="text-[10px] text-slate-500 font-mono">
                            {(ov.totalBytes / 1024).toFixed(1)} KB
                          </div>
                        </div>

                        <div className="space-y-0.5">
                          <div className="text-slate-500 text-[10px] uppercase font-semibold tracking-wider">
                            Declarações
                          </div>
                          <div className="font-mono font-bold text-cyan-300 text-sm tabular-nums">
                            {ov.totalFunctions} funcs
                          </div>
                          <div className="text-[10px] text-slate-500 font-mono">
                            {ov.totalClasses} classes
                          </div>
                        </div>

                        <div className="space-y-0.5 col-span-2 sm:col-span-1">
                          <div className="text-slate-500 text-[10px] uppercase font-semibold tracking-wider flex items-center gap-1">
                            <Clock className="w-3 h-3 text-slate-400" />
                            Última Modificação
                          </div>
                          <div className="font-mono text-slate-300 text-xs truncate tabular-nums">
                            {formatDate(ov.lastModified)}
                          </div>
                          <div className="text-[10px] text-slate-500">Tree-sitter pronto</div>
                        </div>
                      </div>

                      {/* Right: Actions */}
                      <div className="flex md:flex-col items-center justify-end gap-2 md:border-l md:border-slate-800 md:pl-5 shrink-0">
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            onSelectProject(ov.name);
                            setManagerTab('files');
                          }}
                          className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs font-medium border border-slate-700 flex items-center gap-1.5 transition w-full justify-center"
                          title="Ver e gerenciar arquivos deste projeto"
                        >
                          <FileCode className="w-3.5 h-3.5 text-cyan-400" />
                          <span>Ver Arquivos</span>
                        </button>

                        <div className="flex items-center gap-2 w-full">
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              handleRunAudit(ov.name);
                            }}
                            className="p-1.5 bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-emerald-400 rounded-lg border border-slate-800 transition flex-1 flex justify-center"
                            title="Auditar conformidade de isolamento de caminho"
                          >
                            <ShieldCheck className="w-3.5 h-3.5" />
                          </button>

                          <button
                            onClick={(e) => handleDeleteProject(ov.name, e)}
                            className="p-1.5 bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-red-400 rounded-lg border border-slate-800 transition flex-1 flex justify-center"
                            title="Remover projeto e seu workspace"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* Isolation Compliance Card */}
              {auditReport && (
                <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-5 space-y-3 animate-in fade-in duration-150">
                  <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                    <div className="flex items-center gap-2">
                      <ShieldCheck className="w-4 h-4 text-emerald-400" />
                      <span className="font-semibold text-sm text-slate-100">
                        Auditoria de Isolamento: Projeto '{auditReport.projectName}'
                      </span>
                    </div>
                    <span className="font-mono text-xs px-2.5 py-0.5 rounded-full bg-emerald-950 text-emerald-300 border border-emerald-800">
                      {auditReport.isIsolated
                        ? `✓ 100% Hermético (${auditReport.totalFiles} arquivos verificados, 0 vazamentos)`
                        : `Atenção: ${auditReport.violationCount} violações`}
                    </span>
                  </div>

                  <p className="text-xs text-slate-400">
                    O verificador de fronteiras atesta que todos os arquivos do projeto residem estritamente dentro de{' '}
                    <code className="text-cyan-300 font-mono">{auditReport.projectRoot}</code>, impedindo qualquer acesso ou contaminação com workspaces adjacentes.
                  </p>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 font-mono text-[11px] pt-1">
                    {auditReport.files.map((file: any, idx: number) => (
                      <div
                        key={idx}
                        className="flex items-center justify-between p-2 rounded-lg bg-slate-950 border border-slate-850"
                      >
                        <span className="text-cyan-300 truncate max-w-xs">{file.relativePath}</span>
                        <span className="text-emerald-400 text-[10px] shrink-0">✓ Restrito ao Root</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* TAB 2: FILES & WORKSPACE MANAGER VIEW */}
          {managerTab === 'files' && (
            <div className="space-y-5 animate-in fade-in duration-150">
              {/* Git Status Indicator & Summary Panel */}
              <GitStatusPanel
                activeProject={activeProject}
                projectPath={currentProjectObj?.path}
              />

              <div className="space-y-4">
                {/* Control bar */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-slate-900/90 border border-slate-800 p-4 rounded-2xl">
                  <div>
                    <h4 className="font-semibold text-sm text-slate-100 flex items-center gap-2">
                      <FileCode className="w-4 h-4 text-cyan-400" />
                      Arquivos do Workspace: <span className="text-cyan-400 font-mono">{activeProject}</span>
                    </h4>
                    <p className="text-xs text-slate-400 font-mono mt-0.5">
                      Diretório Raiz Isolado: {currentProjectObj?.path || `/projects/${activeProject}`}
                    </p>
                  </div>

                  <div className="flex items-center gap-2">
                    {/* View mode toggle (Tree vs Grid) */}
                    <div className="flex items-center gap-1 bg-slate-950 p-0.5 rounded-lg border border-slate-800">
                      <button
                        onClick={() => setFileViewMode('tree')}
                        className={`px-2.5 py-1 rounded-md text-xs font-medium flex items-center gap-1.5 transition ${
                          fileViewMode === 'tree'
                            ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 shadow-xs'
                            : 'text-slate-400 hover:text-slate-200'
                        }`}
                        title="Visualizar em árvore de diretórios"
                      >
                        <ListTree className="w-3.5 h-3.5" />
                        <span>Árvore</span>
                      </button>

                      <button
                        onClick={() => setFileViewMode('grid')}
                        className={`px-2.5 py-1 rounded-md text-xs font-medium flex items-center gap-1.5 transition ${
                          fileViewMode === 'grid'
                            ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 shadow-xs'
                            : 'text-slate-400 hover:text-slate-200'
                        }`}
                        title="Visualizar em grade simples"
                      >
                        <LayoutGrid className="w-3.5 h-3.5" />
                        <span>Grade</span>
                      </button>
                    </div>

                    <button
                      onClick={() => handleOpenCreateModal()}
                      className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg border border-slate-700 text-xs font-medium flex items-center gap-1.5 transition"
                    >
                      <FilePlus className="w-3.5 h-3.5 text-cyan-400" />
                      <span>Novo Arquivo</span>
                    </button>
                  </div>
                </div>

                {/* Modal: New File */}
                {showNewFileModal && (
                  <div className="bg-slate-950 border border-slate-800 p-4 rounded-xl space-y-2.5 max-w-sm">
                    <label className="block text-[11px] text-slate-300 font-medium">
                      Nome / Caminho relativo do arquivo:
                    </label>
                    <input
                      type="text"
                      placeholder="Ex: parser.py, routes/user.ts, main.go"
                      value={newFileName}
                      onChange={(e) => setNewFileName(e.target.value)}
                      className="w-full bg-slate-900 border border-slate-700 rounded-lg p-2 text-xs text-slate-200 focus:outline-none focus:border-cyan-500 font-mono"
                      autoFocus
                    />
                    <div className="flex justify-end gap-2 pt-1">
                      <button
                        onClick={() => setShowNewFileModal(false)}
                        className="px-3 py-1 bg-slate-800 text-slate-300 rounded text-xs"
                      >
                        Cancelar
                      </button>
                      <button
                        onClick={handleCreateFile}
                        disabled={!newFileName.trim()}
                        className="px-3 py-1 bg-cyan-600 disabled:opacity-50 text-white rounded text-xs font-medium"
                      >
                        Criar Arquivo
                      </button>
                    </div>
                  </div>
                )}

                {/* VIEW 1: TREE VIEW NAVIGATOR (DUAL PANE) */}
                {fileViewMode === 'tree' ? (
                  <div className="grid grid-cols-1 md:grid-cols-12 gap-5 items-start">
                    {/* Left Pane: Tree View Sidebar */}
                    <div className="md:col-span-5 lg:col-span-4 h-[580px]">
                      <FileTreeNavigator
                        files={projectFiles}
                        activeFile={activeFile}
                        activeProject={activeProject}
                        projectPath={currentProjectObj?.path}
                        onSelectFile={onSelectFile}
                        onDeleteFile={handleDeleteFile}
                        onOpenCreateModal={handleOpenCreateModal}
                      />
                    </div>

                    {/* Right Pane: Active File Inspector & Preview */}
                    <div className="md:col-span-7 lg:col-span-8 bg-slate-900/90 border border-slate-800 rounded-2xl flex flex-col h-[580px] overflow-hidden">
                      {/* File Header */}
                      <div className="p-3.5 border-b border-slate-800 flex items-center justify-between bg-slate-950/40 shrink-0">
                        <div className="flex items-center gap-2 truncate">
                          <FileCode className="w-4 h-4 text-cyan-400 shrink-0" />
                          <span className="font-mono text-xs font-semibold text-slate-200 truncate">
                            {activeFile}
                          </span>
                          <span className="text-[10px] uppercase font-mono px-2 py-0.5 rounded bg-slate-800 text-cyan-300">
                            {activeFile.split('.').pop() || 'file'}
                          </span>
                        </div>

                        <div className="flex items-center gap-2 shrink-0">
                          {onNavigateToAST && (
                            <button
                              onClick={onNavigateToAST}
                              className="px-2.5 py-1 bg-cyan-600/20 hover:bg-cyan-600/30 text-cyan-300 border border-cyan-500/40 rounded-lg text-xs font-medium flex items-center gap-1.5 transition"
                              title="Abrir este arquivo no AST Explorer"
                            >
                              <ExternalLink className="w-3.5 h-3.5" />
                              <span>AST Explorer</span>
                            </button>
                          )}

                          <button
                            onClick={(e) => handleDeleteFile(activeFile, e)}
                            className="p-1.5 text-slate-400 hover:text-red-400 hover:bg-slate-800 rounded-lg border border-slate-800 transition"
                            title="Excluir arquivo ativo"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </div>

                      {/* File Metrics Banner */}
                      <div className="px-4 py-2 bg-slate-950/20 border-b border-slate-800/80 flex items-center justify-between text-[11px] text-slate-400 font-mono shrink-0">
                        <div className="flex items-center gap-4">
                          <span>
                            Linhas: <strong className="text-slate-200">{activeFileContent.split('\n').length}</strong>
                          </span>
                          <span>
                            Caracteres: <strong className="text-slate-200">{activeFileContent.length}</strong>
                          </span>
                          <span>
                            Bytes: <strong className="text-slate-200">{(new Blob([activeFileContent]).size)} B</strong>
                          </span>
                        </div>
                        <span className="text-slate-500">Preview somente-leitura</span>
                      </div>

                      {/* Code Preview Area */}
                      <div className="flex-1 overflow-auto p-4 bg-[#0a0f1d] font-mono text-xs text-slate-300 leading-relaxed">
                        {loadingFileContent ? (
                          <div className="h-full flex items-center justify-center text-slate-500 italic">
                            Carregando conteúdo do arquivo...
                          </div>
                        ) : activeFileContent ? (
                          <pre className="tab-4">
                            {activeFileContent.split('\n').map((line, idx) => (
                              <div key={idx} className="flex hover:bg-slate-900/60 transition px-1 rounded">
                                <span className="w-10 text-slate-600 select-none text-right pr-4 shrink-0 tabular-nums">
                                  {idx + 1}
                                </span>
                                <span className="flex-1 whitespace-pre-wrap break-all">{line || ' '}</span>
                              </div>
                            ))}
                          </pre>
                        ) : (
                          <div className="h-full flex items-center justify-center text-slate-500 italic">
                            Arquivo vazio ou nenhum conteúdo disponível.
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                ) : (
                  /* VIEW 2: FLAT GRID VIEW */
                  <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-5">
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2.5">
                      {projectFiles.map((file) => {
                        const isSelected = activeFile === file;
                        return (
                          <div
                            key={file}
                            onClick={() => onSelectFile(file)}
                            className={`p-3 rounded-xl border text-xs flex items-center justify-between cursor-pointer transition group ${
                              isSelected
                                ? 'bg-cyan-950/40 border-cyan-500/50 text-cyan-200 shadow-sm'
                                : 'bg-slate-950 border-slate-850 hover:border-slate-700 text-slate-300'
                            }`}
                          >
                            <div className="flex items-center gap-2.5 truncate">
                              <FileCode className="w-4 h-4 text-cyan-400 shrink-0" />
                              <span className="font-mono truncate">{file}</span>
                            </div>

                            <div className="flex items-center gap-1.5 shrink-0">
                              {isSelected && (
                                <span className="text-[10px] text-cyan-400 font-medium px-1.5 py-0.5 rounded bg-cyan-900/40 font-mono">
                                  Ativo
                                </span>
                              )}
                              <button
                                onClick={(e) => handleDeleteFile(file, e)}
                                className="p-1 text-slate-400 hover:text-red-400 hover:bg-slate-800 rounded opacity-0 group-hover:opacity-100 transition"
                                title="Excluir arquivo"
                              >
                                <Trash2 className="w-3.5 h-3.5" />
                              </button>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* MODAL: SCAN DIRECTORY (PICK LOCAL FOLDER PATH & CONFIGURE ISOLATED PROJECT) */}
          {showScanModal && (
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-xs animate-in fade-in duration-150">
              <div className="bg-slate-900 border border-slate-700 p-6 rounded-2xl space-y-5 max-w-lg w-full shadow-2xl">
                <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                  <div className="flex items-center gap-2.5">
                    <FolderSearch className="w-5 h-5 text-cyan-400" />
                    <div>
                      <h4 className="font-semibold text-sm text-slate-100">
                        Escanear Diretório Local
                      </h4>
                      <p className="text-[11px] text-slate-400">
                        Adicione uma pasta local automaticamente como novo projeto isolado
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={() => setShowScanModal(false)}
                    className="p-1 text-slate-400 hover:text-slate-200 rounded-lg hover:bg-slate-800"
                  >
                    &times;
                  </button>
                </div>

                {/* Scan Mode Switcher */}
                <div className="flex items-center gap-1 bg-slate-950 p-1 rounded-xl border border-slate-800 text-xs">
                  <button
                    onClick={() => {
                      setScanMode('server');
                      setScanError(null);
                    }}
                    className={`flex-1 py-1.5 rounded-lg font-medium flex items-center justify-center gap-1.5 transition ${
                      scanMode === 'server'
                        ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 shadow-xs'
                        : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    <HardDrive className="w-3.5 h-3.5" />
                    <span>Caminho do Sistema</span>
                  </button>

                  <button
                    onClick={() => {
                      setScanMode('browser');
                      setScanError(null);
                    }}
                    className={`flex-1 py-1.5 rounded-lg font-medium flex items-center justify-center gap-1.5 transition ${
                      scanMode === 'browser'
                        ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 shadow-xs'
                        : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    <FolderUp className="w-3.5 h-3.5" />
                    <span>Pasta do Computador</span>
                  </button>
                </div>

                {/* Error Banner */}
                {scanError && (
                  <div className="p-3 bg-red-950/60 border border-red-800/80 rounded-xl text-xs text-red-200 flex items-start gap-2">
                    <AlertCircle className="w-4 h-4 text-red-400 shrink-0 mt-0.5" />
                    <span>{scanError}</span>
                  </div>
                )}

                {/* MODE 1: SCAN HOST SERVER PATH */}
                {scanMode === 'server' && (
                  <div className="space-y-3.5 text-xs">
                    <div>
                      <div className="flex items-center justify-between mb-1">
                        <label className="text-slate-300 font-medium">
                          Caminho do Diretório: <span className="text-red-400">*</span>
                        </label>
                        <span className="text-[10px] text-slate-500 font-mono">Ex: /workspace, ./src</span>
                      </div>
                      <div className="relative">
                        <HardDrive className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
                        <input
                          type="text"
                          placeholder="/workspace/meu-servico ou ./src"
                          value={scanServerPath}
                          onChange={(e) => setScanServerPath(e.target.value)}
                          className="w-full bg-slate-950 border border-slate-800 rounded-lg pl-8 pr-2.5 py-2 text-slate-200 text-xs focus:outline-none focus:border-cyan-500 font-mono"
                        />
                      </div>

                      {/* Quick preset badges */}
                      <div className="flex items-center gap-1.5 mt-2">
                        <span className="text-[10px] text-slate-500">Sugestões rápidas:</span>
                        {['/workspace', './src', '/projects'].map((p) => (
                          <button
                            key={p}
                            type="button"
                            onClick={() => setScanServerPath(p)}
                            className="text-[10px] px-2 py-0.5 rounded bg-slate-800 hover:bg-slate-700 text-cyan-300 font-mono border border-slate-700"
                          >
                            {p}
                          </button>
                        ))}
                      </div>
                    </div>

                    <div className="grid grid-cols-2 gap-3">
                      <div>
                        <label className="block text-slate-300 font-medium mb-1">
                          Nome do Projeto (Opcional):
                        </label>
                        <input
                          type="text"
                          placeholder="Detectado da pasta"
                          value={scanCustomName}
                          onChange={(e) => setScanCustomName(e.target.value)}
                          className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-slate-200 text-xs focus:outline-none focus:border-cyan-500 font-mono"
                        />
                      </div>

                      <div>
                        <label className="block text-slate-300 font-medium mb-1">
                          Limite de Arquivos:
                        </label>
                        <select
                          value={scanMaxFiles}
                          onChange={(e) => setScanMaxFiles(Number(e.target.value))}
                          className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-slate-200 text-xs focus:outline-none focus:border-cyan-500"
                        >
                          <option value={50}>50 arquivos</option>
                          <option value={100}>100 arquivos</option>
                          <option value={150}>150 arquivos</option>
                          <option value={200}>200 arquivos</option>
                        </select>
                      </div>
                    </div>

                    <div className="bg-slate-950/60 p-3 rounded-xl border border-slate-850 text-[11px] text-slate-400 space-y-1">
                      <div className="font-semibold text-slate-300">Filtros Automáticos Aplicados:</div>
                      <p>
                        Ignora automaticamente <code className="text-cyan-400 font-mono">node_modules</code>, <code className="text-cyan-400 font-mono">.git</code>, <code className="text-cyan-400 font-mono">dist</code> e pastas virtuais. Analisa apenas arquivos de código (.py, .ts, .go, .rs, .json, etc.).
                      </p>
                    </div>
                  </div>
                )}

                {/* MODE 2: SCAN LOCAL FOLDER VIA BROWSER PICKER */}
                {scanMode === 'browser' && (
                  <div className="space-y-3.5 text-xs">
                    {/* Hidden input supporting directory upload */}
                    <input
                      type="file"
                      ref={fileInputRef}
                      // @ts-ignore: webkitdirectory and directory are browser standards
                      webkitdirectory=""
                      directory=""
                      multiple
                      className="hidden"
                      onChange={handleBrowserFolderChange}
                    />

                    {browserFiles.length === 0 ? (
                      <div
                        onClick={() => fileInputRef.current?.click()}
                        className="p-6 border-2 border-dashed border-slate-700 hover:border-cyan-500/80 rounded-2xl bg-slate-950 flex flex-col items-center justify-center cursor-pointer transition text-center group"
                      >
                        <div className="w-10 h-10 rounded-xl bg-cyan-950/60 border border-cyan-800/80 flex items-center justify-center text-cyan-400 mb-2 group-hover:scale-110 transition">
                          <FolderUp className="w-5 h-5" />
                        </div>
                        <span className="font-semibold text-slate-200 text-xs">
                          Clique para escolher uma pasta no seu computador
                        </span>
                        <span className="text-[11px] text-slate-500 mt-1">
                          O navegador irá ler os arquivos de código e estruturá-los em um workspace isolado.
                        </span>
                      </div>
                    ) : (
                      <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-2.5">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                            <span className="font-semibold text-slate-200">
                              Pasta Selecionada: <span className="text-cyan-400 font-mono">{browserFolderName}</span>
                            </span>
                          </div>
                          <button
                            type="button"
                            onClick={() => fileInputRef.current?.click()}
                            className="text-[10px] text-slate-400 hover:text-slate-200 underline"
                          >
                            Trocar pasta
                          </button>
                        </div>

                        <div className="text-[11px] text-slate-400 font-mono">
                          {browserFiles.length} arquivos de código identificados para importação.
                        </div>

                        <div className="max-h-28 overflow-y-auto space-y-1 font-mono text-[10px] text-slate-300 pr-1">
                          {browserFiles.slice(0, 10).map((f) => (
                            <div key={f.path} className="truncate bg-slate-900 px-2 py-0.5 rounded">
                              {f.path}
                            </div>
                          ))}
                          {browserFiles.length > 10 && (
                            <div className="text-slate-500 italic pl-1">
                              + {browserFiles.length - 10} outros arquivos...
                            </div>
                          )}
                        </div>

                        <div>
                          <label className="block text-slate-300 font-medium mb-1">
                            Nome do Projeto Isolado:
                          </label>
                          <input
                            type="text"
                            value={scanCustomName}
                            onChange={(e) => setScanCustomName(e.target.value)}
                            className="w-full bg-slate-900 border border-slate-800 rounded-lg p-2 text-slate-200 text-xs focus:outline-none focus:border-cyan-500 font-mono"
                          />
                        </div>
                      </div>
                    )}
                  </div>
                )}

                {/* Footer Controls */}
                <div className="flex justify-end gap-2 pt-2 border-t border-slate-800">
                  <button
                    onClick={() => setShowScanModal(false)}
                    className="px-3.5 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-xs transition"
                  >
                    Cancelar
                  </button>

                  {scanMode === 'server' ? (
                    <button
                      onClick={handleScanServerDirectory}
                      disabled={scanLoading || !scanServerPath.trim()}
                      className="px-4 py-1.5 bg-cyan-600 hover:bg-cyan-500 disabled:opacity-50 text-white rounded-lg text-xs font-semibold flex items-center gap-1.5 transition"
                    >
                      {scanLoading ? (
                        <>
                          <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                          <span>Escanear...</span>
                        </>
                      ) : (
                        <>
                          <FolderSearch className="w-3.5 h-3.5" />
                          <span>Escanear e Adicionar</span>
                        </>
                      )}
                    </button>
                  ) : (
                    <button
                      onClick={handleImportBrowserFolder}
                      disabled={scanLoading || browserFiles.length === 0}
                      className="px-4 py-1.5 bg-cyan-600 hover:bg-cyan-500 disabled:opacity-50 text-white rounded-lg text-xs font-semibold flex items-center gap-1.5 transition"
                    >
                      {scanLoading ? (
                        <>
                          <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                          <span>Importando...</span>
                        </>
                      ) : (
                        <>
                          <Upload className="w-3.5 h-3.5" />
                          <span>Importar como Projeto Isolado</span>
                        </>
                      )}
                    </button>
                  )}
                </div>
              </div>
            </div>
          )}

          {/* Modal: New Project */}
          {showNewProjectModal && (
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-xs animate-in fade-in duration-150">
              <div className="bg-slate-900 border border-slate-700 p-5 rounded-2xl space-y-4 max-w-lg w-full shadow-2xl">
                <div className="flex items-center justify-between border-b border-slate-800 pb-2">
                  <h4 className="font-semibold text-sm text-slate-100 flex items-center gap-2">
                    <FolderGit2 className="w-4 h-4 text-cyan-400" />
                    Cadastrar Novo Projeto com Caminho Isolado
                  </h4>
                </div>

                <div className="space-y-3 text-xs">
                  <div>
                    <label className="block text-slate-300 font-medium mb-1">
                      Nome do Projeto: <span className="text-red-400">*</span>
                    </label>
                    <input
                      type="text"
                      placeholder="Ex: auth-service, mobile-app, parser-core"
                      value={newProjName}
                      onChange={(e) => handleNameChange(e.target.value)}
                      className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2.5 text-slate-200 text-xs focus:outline-none focus:border-cyan-500 font-mono"
                      autoFocus
                    />
                  </div>

                  <div>
                    <div className="flex items-center justify-between mb-1">
                      <label className="block text-slate-300 font-medium">
                        Caminho Raiz do Projeto (Path): <span className="text-red-400">*</span>
                      </label>
                      <span className="text-[10px] text-cyan-400 font-mono">
                        {pathAutoGenerated ? 'Gerado automaticamente' : 'Caminho personalizado'}
                      </span>
                    </div>
                    <div className="relative">
                      <HardDrive className="w-3.5 h-3.5 text-slate-400 absolute left-2.5 top-1/2 -translate-y-1/2" />
                      <input
                        type="text"
                        placeholder="Ex: /workspace/auth-service ou /home/dev/projects/api"
                        value={newProjPath}
                        onChange={(e) => handlePathChange(e.target.value)}
                        className="w-full bg-slate-950 border border-slate-800 rounded-lg pl-8 pr-2.5 py-2 text-slate-200 text-xs focus:outline-none focus:border-cyan-500 font-mono"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-slate-300 font-medium mb-1">
                      Descrição (Opcional):
                    </label>
                    <input
                      type="text"
                      placeholder="Ex: Microsserviço de autenticação e tokens JWT"
                      value={newProjDesc}
                      onChange={(e) => setNewProjDesc(e.target.value)}
                      className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2.5 text-slate-200 text-xs focus:outline-none focus:border-cyan-500"
                    />
                  </div>
                </div>

                <div className="flex justify-end gap-2 pt-2 border-t border-slate-800">
                  <button
                    onClick={() => setShowNewProjectModal(false)}
                    className="px-3.5 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-xs transition"
                  >
                    Cancelar
                  </button>
                  <button
                    onClick={handleCreateProject}
                    disabled={!newProjName.trim()}
                    className="px-4 py-1.5 bg-cyan-600 hover:bg-cyan-500 disabled:opacity-50 text-white rounded-lg text-xs font-semibold transition"
                  >
                    Criar e Isolar Projeto
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
